name: Minify and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        npm install -g html-minifier uglify-js csso-cli @node-minify/cli

    - name: Minify Code
      run: |
        # Minify HTML
        html-minifier --input-dir . --output-dir . --file-ext html --collapse-whitespace --remove-comments --minify-js --minify-css
        
        # Minify JS
        uglifyjs ./script.js --compress --mangle --output ./script.js 
    
        # Minify CSS (create .min.css versions)
        perl -0777 -pe 's/\/\*.*?\*\///gs; s/^\s+|\s+$//gm; s/[ \t]+/ /g;' ./css/style.css > ./css/style.min.css
        perl -0777 -pe 's/\/\*.*?\*\///gs; s/^\s+|\s+$//gm; s/[ \t]+/ /g;' ./css/infinite_scroll.css > ./css/infinite_scroll.min.css
        perl -0777 -pe 's/\/\*.*?\*\///gs; s/^\s+|\s+$//gm; s/[ \t]+/ /g;' ./css/image_hover.css > ./css/image_hover.min.css
    
        # Update HTML to reference minified CSS
        find . -name "*.html" -exec sed -i 's/style\.css/style.min.css/g' {} +
        find . -name "*.html" -exec sed -i 's/infinite_scroll\.css/infinite_scroll.min.css/g' {} +
        find . -name "*.html" -exec sed -i 's/image_hover\.css/image_hover.min.css/g' {} +     


    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: .
